name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VIRTUAL_ENV: venv
      PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip
      PYTHON_VERSION: "3.11"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m venv $VIRTUAL_ENV
          source $VIRTUAL_ENV/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare config
        run: |
          mkdir -p docs

      - name: Run tests
        run: |
          source $VIRTUAL_ENV/bin/activate
          python -m unittest discover -s tests -p "*.py"
          
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
